configs = {
    "MDuo": {
        "__cls__": "MDuo",
        "item_len_sec": 10,
        "sample_rate": 16000,
        "feature_dim": 3840,
        "extract_kws": {
            "pooled": True,
        },
    },
    "AudioMAE": {
        "__cls__": "AudioMAE",
        "item_len_sec": 10,
        "sample_rate": 16000,
        "feature_dim": 768,
        "extract_kws": {
            "pooled": True,
        },
    },
    "VGGishMTAT": {
        "__cls__": "VGGishMTAT",
        "item_len_sec": 3.69,
        "sample_rate": 16000,
        "feature_dim": 512,
    },
    "MULE_1728": {
        "__cls__": "MULE",
        "item_len_sec": 2.99,
        "sample_rate": 16000,
        "feature_dim": 1728,
        "extract_kws": {
            "key": "encoded",
        },
    },
    "MULE_512": {
        "__cls__": "MULE",
        "item_len_sec": 2.99,
        "sample_rate": 16000,
        "feature_dim": 512,
        "extract_kws": {
            "key": "projected",
        },
    },
    "Music2Latent_8192": {
        "__cls__": "MusicLatent",
        "item_len_sec": 3,
        "sample_rate": 44100,
        "feature_dim": 8192,
        "extract_kws": {
            "extract_features": True,
        },
    },
    "Music2Latent_64": {
        "__cls__": "MusicLatent",
        "item_len_sec": 3,
        "sample_rate": 44100,
        "feature_dim": 64,
        "extract_kws": {
            "extract_features": False,
        },
    },
    "PESTO": {
        "__cls__": "PESTO",
        "item_len_sec": 3,
        "sample_rate": 22050,
        "feature_dim": 384,
    },
    "MERT": {
        "__cls__": "MERT",
        "item_len_sec": 3,
        "sample_rate": 24000,
        "feature_dim": 768,
        "extract_kws": {
            "pooled": True,
        },
    },
    "Wav2Vec2": {
        "__cls__": "Wav2Vec2",
        "item_len_sec": 10,
        "sample_rate": 16000,
        "feature_dim": 768,
    },
    "HuBERT": {
        "__cls__": "HuBERT",
        "item_len_sec": 10,
        "sample_rate": 16000,
        "feature_dim": 768,
    },
    "CLAP": {
        "__cls__": "CLAP",
        "item_len_sec": 10,
        "sample_rate": 48000,
        "feature_dim": 512,
    },
    "Whisper": {
        "__cls__": "Whisper",
        "item_len_sec": 10,
        "sample_rate": 16000,
        "feature_dim": 768,
    },
    "UniSpeech": {
        "__cls__": "UniSpeech",
        "item_len_sec": 10,
        "sample_rate": 16000,
        "feature_dim": 768,
    },
    "XVector": {
        "__cls__": "XVector",
        "item_len_sec": 10,
        "sample_rate": 16000,
        "feature_dim": 512,
    },
    "ResNet50_ImageNet": {
        "__cls__": "ResNet50_ImageNet",
        "resize_dim": 256,
        "input_dim": 224,
        "feature_dim": 2048,
        "mean": [0.485, 0.456, 0.406],
        "std": [0.229, 0.224, 0.225],
    },
    "ViT_ImageNet": {
        "__cls__": "ViT_ImageNet",
        "resize_dim": 256,
        "input_dim": 224,
        "feature_dim": 768,
        "mean": [0.485, 0.456, 0.406],
        "std": [0.229, 0.224, 0.225],
    },
    "SimCLR": {
        "__cls__": "SimCLR",
        "resize_dim": 256,
        "input_dim": 224,
        "feature_dim": 2048,
    },
    "DINO": {
        "__cls__": "DINO",
        "resize_dim": 256,
        "input_dim": 224,
        "feature_dim": 2048,
        "mean": [0.485, 0.456, 0.406],
        "std": [0.229, 0.224, 0.225],
    },
    "ViT_MAE": {
        "__cls__": "ViT_MAE",
        "resize_dim": 256,
        "input_dim": 224,
        "feature_dim": 768,
        "mean": [0.5, 0.5, 0.5],
        "std": [0.5, 0.5, 0.5],
    },
    "CLIP": {
        "__cls__": "CLIP",
        "resize_dim": 256,
        "input_dim": 224,
        "feature_dim": 512,
        "mean": [0.48145466, 0.4578275, 0.40821073],
        "std": [0.26862954, 0.26130258, 0.27577711],
    },
    "IJEPA": {
        "__cls__": "IJEPA",
        "resize_dim": 256,
        "input_dim": 224,
        "feature_dim": 1280,
        "mean": [0.485, 0.456, 0.406],
        "std": [0.229, 0.224, 0.225],
    },
}
